name: Keith Waara
favicon: null
layout_spectrum: 0.9294400997459888
typography_spectrum: 0.759504922432825
title: Personal Page
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcdec6'
    - '#b5ae95'
    - '#362d34'
    - '#9e8e79'
    - '#836763'
  brandStrength: 0.8778253742493689
  lightness: 0.3553975257091224
  saturation: 0.9674965373706073
  rhythmicContrast: 0.8256446470040828
purpose: []
